### ISSUE TITLE
Stating dependencies

### ISSUE THREAD

**Issue by briatte** [paulgovan/RiskNetwork#3]
I could not find a list of package dependencies for the app, but I believe that those are
- bnlearn
- d3heatmap
- networkD3
- rhandsontable
- shiny
- shinydashboard

Perhaps it would help to list them somewhere on https://paulgovan.github.io/RiskNetwork/

**Comment by paulgovan** [comment]
Yep, those are them, but really rhandsontable is part of an experimental feature that is currently not working. I think the best solution would be to wrap the app in an [R package](http://r-pkgs.had.co.nz) that would import any missing dependencies automatically. Will let you know when I have a chance to make the update.

**Comment by paulgovan** [comment]
Included package dependencies in DESCRIPTION file
