### ISSUE TITLE
Duplicated publication links at the overview section at the README

### ISSUE THREAD

**Issue by brgas** [paulgovan/RiskNetwork#4]
The links for the publications at the following part of the overview section are the same:

> To learn more about our project, check out this [publication](http://ascelibrary.org/doi/abs/10.1061/(ASCE)CO.1943-7862.0001136). For even more background, see this [publication](http://dx.doi.org/10.1061/(ASCE)CO.1943-7862.0001136).

Minor issue, but I'd really like to read whatever second publication that was supposed to be there.

**Comment by paulgovan** [comment]
Hi @brgas, unfortunately, I'm no longer able to maintain this package. For a more recent package, please see [BayesianNetwork](https://github.com/paulgovan/BayesianNetwork)
